from __future__ import annotations

LENDER_ARCHETYPES = [
    {
        "key": "commercial_bank",
        "display_name": "Commercial Bank",
        "tier_rank": 4,
        "minimum_score": 760,
        "maximum_acceptable_fraud_score": 20,
        "minimum_history_months": 24,
        "minimum_loan_amount": 500_000,
        "maximum_loan_amount": 50_000_000,
        "typical_interest_rate_range": "9% - 13%",
        "typical_processing_time_days": 14,
        "notes": "Usually expects ITR filings, audited financials, and a longer operating track record.",
    },
    {
        "key": "sidbi",
        "display_name": "SIDBI",
        "tier_rank": 3,
        "minimum_score": 720,
        "maximum_acceptable_fraud_score": 35,
        "minimum_history_months": 12,
        "minimum_loan_amount": 500_000,
        "maximum_loan_amount": 30_000_000,
        "typical_interest_rate_range": "8% - 12%",
        "typical_processing_time_days": 10,
        "notes": "Strong fit for formal MSMEs, but sector fit, documentation quality, and scheme eligibility still matter.",
    },
    {
        "key": "nbfc",
        "display_name": "NBFC",
        "tier_rank": 2,
        "minimum_score": 680,
        "maximum_acceptable_fraud_score": 45,
        "minimum_history_months": 6,
        "minimum_loan_amount": 200_000,
        "maximum_loan_amount": 25_000_000,
        "typical_interest_rate_range": "14% - 24%",
        "typical_processing_time_days": 5,
        "notes": "Most practical option for thin-file MSMEs that have usable digital history but are not yet bank-ready.",
    },
    {
        "key": "mfi",
        "display_name": "MFI",
        "tier_rank": 1,
        "minimum_score": 560,
        "maximum_acceptable_fraud_score": 70,
        "minimum_history_months": 3,
        "minimum_loan_amount": 50_000,
        "maximum_loan_amount": 500_000,
        "typical_interest_rate_range": "18% - 28%",
        "typical_processing_time_days": 3,
        "notes": "Best for early-stage working capital needs when the business is still building formal lender credibility.",
    },
]
